-- ============================================
-- 회원 영역
-- ============================================

-- 1. USERS (회원)
CREATE TABLE USERS (
    USER_ID VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    NICKNAME VARCHAR(20) NOT NULL,
    PHONE VARCHAR(14) NULL,
    PROFILE_IMAGE VARCHAR(255) NULL,
    ROLE VARCHAR(20) NOT NULL DEFAULT 'USER',
    USER_STATUS VARCHAR(20) NOT NULL,
    REG_DATE DATE NOT NULL,
    CI VARCHAR(100) NOT NULL,
    DI VARCHAR(100) NOT NULL,
    PASS_CERTIFIED_AT DATE NULL,
    LAST_LOGIN_DATE DATE NULL,
    LOGIN_FAIL_COUNT INT NULL DEFAULT 0,
    UNLOCK_SCHEDULED_AT DATE NULL,
    DELETE_DATE DATE NULL,
    DELETE_TYPE VARCHAR(20) NULL,
    DELETE_DETAIL VARCHAR(500) NULL,
    
    PRIMARY KEY (USER_ID),
    UNIQUE KEY UQ_USERS_CI (CI),
    UNIQUE KEY UQ_USERS_DI (DI)
);

-- 2. OAUTH_ACCOUNT (소셜계정)
CREATE TABLE OAUTH_ACCOUNT (
    OAUTH_ID VARCHAR(255) NOT NULL,
    PROVIDER VARCHAR(20) NOT NULL,
    PROVIDER_USER_ID VARCHAR(50) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    CONNECTED_DATE DATE NOT NULL,
    RELEASE_DATE DATE NULL,
    
    PRIMARY KEY (OAUTH_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
	
	-- 외래키 제약
	CONSTRAINT FK_OAUTH_USER FOREIGN KEY (USER_ID) 
		REFERENCES USERS(USER_ID),
    
    -- UNIQUE 제약 1: 같은 소셜 계정을 여러 회원이 연동 불가
    CONSTRAINT UQ_OAUTH_PROVIDER_USER 
        UNIQUE (PROVIDER, PROVIDER_USER_ID),
    
    -- UNIQUE 제약 2: 한 회원이 같은 제공자를 2번 연동 불가
    CONSTRAINT UQ_OAUTH_USER_PROVIDER 
        UNIQUE (USER_ID, PROVIDER)
		
);



-- 3. BLACKLIST (블랙리스트)
CREATE TABLE BLACKLIST (
    BLACKLIST_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(50) NOT NULL,
    REASON VARCHAR(500) NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    REG_DATE DATE NOT NULL,
    RELEASE_DATE DATE NULL,
    
    PRIMARY KEY (BLACKLIST_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- ============================================
-- 게시판 영역
-- ============================================

-- 4. COMMUNITY_CODE (커뮤니티코드)
CREATE TABLE COMMUNITY_CODE (
    COMMUNITY_CODE_ID INT NOT NULL,
    CATEGORY VARCHAR(20) NOT NULL,
    CODE_NAME VARCHAR(50) NOT NULL,
    
    PRIMARY KEY (COMMUNITY_CODE_ID)
);

-- 5. COMMUNITY (문의&게시물)
CREATE TABLE COMMUNITY (
    COMMUNITY_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(50) NOT NULL,
    COMMUNITY_CODE_ID INT NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT VARCHAR(500) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VIEW_COUNT INT NULL DEFAULT 0,
    FILE_ORIGINAL VARCHAR(255) NULL,
    FILE_UUID VARCHAR(255) NULL,
    ANSWER_CONTENT VARCHAR(500) NULL,
    ANSWERED_AT DATETIME NULL,
    ANSWER_STATUS VARCHAR(20) NULL DEFAULT '답변대기',
    
    PRIMARY KEY (COMMUNITY_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (COMMUNITY_CODE_ID) REFERENCES COMMUNITY_CODE(COMMUNITY_CODE_ID)
);

-- 6. PUSH_CODE (푸시코드)
CREATE TABLE PUSH_CODE (
    PUSH_CODE_ID INT NOT NULL AUTO_INCREMENT,
    CODE_NAME VARCHAR(50) NOT NULL,
    TITLE_TEMPLATE VARCHAR(200) NOT NULL,
    CONTENT_TEMPLATE VARCHAR(500) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (PUSH_CODE_ID)
);

-- 7. PUSH (푸시)
CREATE TABLE PUSH (
    PUSH_ID INT NOT NULL AUTO_INCREMENT,
    RECEIVER_ID VARCHAR(50) NOT NULL,
    PUSH_CODE VARCHAR(20) NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT VARCHAR(500) NOT NULL,
    MODULE_ID VARCHAR(50) NULL,
    MODULE_TYPE VARCHAR(50) NULL,
    SENT_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    READ_AT DATETIME NULL,
    IS_READ CHAR(1) NOT NULL DEFAULT 'N',
    IS_DELETED CHAR(1) NOT NULL DEFAULT 'N',
    
    PRIMARY KEY (PUSH_ID),
    FOREIGN KEY (RECEIVER_ID) REFERENCES USERS(USER_ID)
);

-- ============================================
-- 공통/상품 영역
-- ============================================

-- 8. CATEGORY (카테고리)
CREATE TABLE CATEGORY (
    CATEGORY_ID INT NOT NULL AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(50) NOT NULL,
    
    PRIMARY KEY (CATEGORY_ID)
);


-- 9. PRODUCT (상품)
CREATE TABLE PRODUCT (
    PRODUCT_ID INT NOT NULL AUTO_INCREMENT,
    CATEGORY_ID INT NOT NULL,
    PRODUCT_NAME VARCHAR(30) NOT NULL,
   PRODUCT_STATUS VARCHAR(10) NOT NULL  DEFAULT 'ACTIVE',
    PRICE INT NOT NULL,
    IMAGE VARCHAR(255) NULL,
    
    PRIMARY KEY (PRODUCT_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

-- 10. SUBSCRIPTION (구독)
CREATE TABLE SUBSCRIPTION (
    SUBSCRIPTION_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(50) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    SUBSCRIPTION_STATUS VARCHAR(20) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NULL,
    CANCEL_REASON VARCHAR(255) NULL,
    CANCEL_DATE DATE NULL,
    
    PRIMARY KEY (SUBSCRIPTION_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- ============================================
-- 계좌/카드 영역
-- ============================================

-- 11. ACCOUNT (계좌)
CREATE TABLE ACCOUNT (
    ACCOUNT_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(50) NOT NULL,
    BANK_CODE VARCHAR(10) NOT NULL,
    BANK_NAME VARCHAR(50) NOT NULL,
    ACCOUNT_NUMBER VARCHAR(255) NOT NULL,
    ACCOUNT_HOLDER VARCHAR(50) NOT NULL,
    IS_VERIFIED CHAR(1) NOT NULL DEFAULT 'N',
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VERIFY_DATE DATETIME NULL,
    
    PRIMARY KEY (ACCOUNT_ID),
    UNIQUE KEY UQ_ACCOUNT_USER (USER_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 12. USER_CARD (사용자카드)
CREATE TABLE USER_CARD (
    USER_ID VARCHAR(50) NOT NULL,
    BILLING_KEY VARCHAR(255) NOT NULL,
    CARD_COMPANY VARCHAR(50) NOT NULL,
    CARD_NUMBER VARCHAR(20) NOT NULL,
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (USER_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- ============================================
-- 파티 영역
-- ============================================

-- 13. PARTY (파티)
CREATE TABLE PARTY (
    PARTY_ID INT NOT NULL AUTO_INCREMENT,
    PARTY_LEADER_ID VARCHAR(50) NOT NULL,
    PARTY_STATUS VARCHAR(20) NOT NULL DEFAULT 'RECRUITING',
    MAX_MEMBERS INT NOT NULL,
    CURRENT_MEMBERS INT NOT NULL DEFAULT 1,
    MONTHLY_FEE INT NOT NULL,
    OTT_ID VARCHAR(100) NULL,
    OTT_PASSWORD VARCHAR(255) NULL,
    ACCOUNT_ID INT NULL,
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    START_DATE DATETIME NULL,
    END_DATE DATETIME NULL,
    
    PRIMARY KEY (PARTY_ID),
    FOREIGN KEY (PARTY_LEADER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

-- 14. PARTY_MEMBER (파티멤버)
CREATE TABLE PARTY_MEMBER (
    PARTY_MEMBER_ID INT NOT NULL AUTO_INCREMENT,
    PARTY_ID INT NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    MEMBER_ROLE VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    MEMBER_STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    JOIN_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    WITHDRAW_DATE DATETIME NULL,
    
    PRIMARY KEY (PARTY_MEMBER_ID),
    FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    
    -- UNIQUE 제약: 같은 회원이 같은 파티에 중복 가입 방지
    CONSTRAINT UQ_PARTY_MEMBER_USER 
        UNIQUE (PARTY_ID, USER_ID)
);

-- ============================================
-- 결제/보증금 영역
-- ============================================

-- 15. DEPOSIT (보증금)
CREATE TABLE DEPOSIT (
    DEPOSIT_ID INT NOT NULL AUTO_INCREMENT,
    PARTY_ID INT NOT NULL,
    PARTY_MEMBER_ID INT NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    DEPOSIT_TYPE VARCHAR(20) NOT NULL,
    DEPOSIT_AMOUNT INT NOT NULL,
    DEPOSIT_STATUS VARCHAR(20) NOT NULL DEFAULT 'PAID',
    PAYMENT_DATE DATETIME NOT NULL,
    REFUND_DATE DATETIME NULL,
    REFUND_AMOUNT INT NULL,
    TRANSACTION_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (DEPOSIT_ID),
    FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID),
    FOREIGN KEY (PARTY_MEMBER_ID) REFERENCES PARTY_MEMBER(PARTY_MEMBER_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 16. PAYMENT (결제)
CREATE TABLE PAYMENT (
    PAYMENT_ID INT NOT NULL AUTO_INCREMENT,
    PARTY_ID INT NOT NULL,
    PARTY_MEMBER_ID INT NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    PAYMENT_TYPE VARCHAR(20) NOT NULL,
    PAYMENT_AMOUNT INT NOT NULL,
    PAYMENT_STATUS VARCHAR(20) NOT NULL,
    PAYMENT_METHOD VARCHAR(20) NULL DEFAULT 'CARD',
    PAYMENT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TOSS_PAYMENT_KEY VARCHAR(255) NULL,
    ORDER_ID VARCHAR(100) NULL,
    CARD_NUMBER VARCHAR(20) NULL,
    CARD_COMPANY VARCHAR(50) NULL,
    TARGET_MONTH VARCHAR(7) NOT NULL,
    
    PRIMARY KEY (PAYMENT_ID),
    FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID),
    FOREIGN KEY (PARTY_MEMBER_ID) REFERENCES PARTY_MEMBER(PARTY_MEMBER_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- ============================================
-- 정산 영역
-- ============================================

-- 17. SETTLEMENT (정산)
CREATE TABLE SETTLEMENT (
    SETTLEMENT_ID INT NOT NULL AUTO_INCREMENT,
    PARTY_ID INT NOT NULL,
    PARTY_LEADER_ID VARCHAR(50) NOT NULL,
    ACCOUNT_ID INT NULL,
    SETTLEMENT_MONTH VARCHAR(7) NOT NULL,
    SETTLEMENT_TYPE VARCHAR(20) NOT NULL DEFAULT 'MONTHLY',
    TOTAL_AMOUNT INT NOT NULL,
    COMMISSION_RATE DECIMAL(3,2) NOT NULL DEFAULT 0.15,
    COMMISSION_AMOUNT INT NOT NULL,
    NET_AMOUNT INT NOT NULL,
    SETTLEMENT_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    SETTLEMENT_DATE DATETIME NULL,
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (SETTLEMENT_ID),
    FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID),
    FOREIGN KEY (PARTY_LEADER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

-- 18. SETTLEMENT_DETAIL (정산상세)
CREATE TABLE SETTLEMENT_DETAIL (
    DETAIL_ID INT NOT NULL AUTO_INCREMENT,
    SETTLEMENT_ID INT NOT NULL,
    PAYMENT_ID INT NOT NULL,
    PARTY_MEMBER_ID INT NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    PAYMENT_AMOUNT INT NOT NULL,
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (DETAIL_ID),
    FOREIGN KEY (SETTLEMENT_ID) REFERENCES SETTLEMENT(SETTLEMENT_ID),
    FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID),
    FOREIGN KEY (PARTY_MEMBER_ID) REFERENCES PARTY_MEMBER(PARTY_MEMBER_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);